version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        TARGETARCH: ${TARGETARCH:-${BUILDPLATFORM_ARCH:-amd64}}
    container_name: app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: app_webserver
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app_data:
    driver: local
