name: Test Container Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-build:
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
            arch: amd64
          - platform: linux/arm64
            runner: arm64.ubuntu-latest  # uses partner runner
            arch: arm64

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test build for ${{ matrix.platform }}
        uses: docker/build-push-action@v5
        with:
          context: ./docker/php
          file: ./docker/php/Dockerfile
          platforms: ${{ matrix.platform }}
          push: false
          tags: laravel-instantclient:test-${{ matrix.arch }}
          load: true
